# Generated by Django 3.2.10 on 2021-12-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='id_faq',
            new_name='id',
        ),
    ]
