# Generated by Django 3.2.10 on 2021-12-28 12:53

from django.db import migrations, models
import util.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fr', models.CharField(max_length=254)),
                ('en', models.CharField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'description',
            },
            bases=(util.utils.DefaultModel, models.Model),
        ),
    ]
