# Generated by Django 3.2.10 on 2021-12-28 11:15

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(upload_to=image.models.upload_update_image)),
                ('alt', models.CharField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
